# Generated by Django 5.2.8 on 2025-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
