# Generated by Django 5.2.8 on 2025-11-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_publisher_city_publisher_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sinopse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
