# Generated by Django 5.2.8 on 2025-11-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_gender_book_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
