# Generated by Django 5.2.8 on 2025-11-25 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_date', models.DateTimeField(auto_now_add=True)),
                ('expected_date', models.DateField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('fine_paid', models.BooleanField(blank=True, default=None, null=True)),
                ('copies_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.copies')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'booking'), ('R', 'renewal'), ('PS', 'purchase_suggestion')], default='B', max_length=2)),
                ('status', models.CharField(choices=[('P', 'peding'), ('A', 'approved'), ('R', 'rejected')], default='P', max_length=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
