# Generated by Django 5.2.8 on 2025-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='daily_fine_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='profiletype',
            name='max_books',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
